import { Bookmark, Collection } from './types';

export const seedCollections: Collection[] = [
  { id: 'col-dev', name: 'Development', icon: '💻', color: '#2563eb' },
  { id: 'col-design', name: 'Design', icon: '🎨', color: '#7c3aed' },
  { id: 'col-productivity', name: 'Productivity', icon: '⚡', color: '#f59e0b' },
  { id: 'col-learning', name: 'Learning', icon: '📚', color: '#10b981' },
  { id: 'col-news', name: 'News & Media', icon: '📰', color: '#ef4444' },
];

export const seedBookmarks: Bookmark[] = [
  {
    id: 'bm-1',
    url: 'https://nextjs.org',
    title: 'Next.js by Vercel',
    description: 'The React Framework for the Web. Used by some of the world\'s largest companies.',
    favicon: 'https://nextjs.org/favicon.ico',
    previewImage: 'https://nextjs.org/static/twitter-cards/home.jpg',
    tags: ['react', 'framework', 'frontend'],
    collectionId: 'col-dev',
    notes: 'Primary framework for new projects',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'bm-2',
    url: 'https://tailwindcss.com',
    title: 'Tailwind CSS',
    description: 'A utility-first CSS framework packed with classes that can be composed to build any design.',
    favicon: 'https://tailwindcss.com/favicons/favicon.ico',
    previewImage: 'https://tailwindcss.com/_next/static/media/social-card-large.a6e71726.jpg',
    tags: ['css', 'framework', 'frontend'],
    collectionId: 'col-dev',
    notes: '',
    createdAt: '2026-03-02T14:30:00Z',
  },
  {
    id: 'bm-3',
    url: 'https://github.com',
    title: 'GitHub',
    description: 'The world\'s leading software development platform. Build, ship, and maintain software.',
    favicon: 'https://github.com/favicon.ico',
    tags: ['git', 'collaboration', 'code'],
    collectionId: 'col-dev',
    notes: 'Check trending repos weekly',
    createdAt: '2026-03-03T09:15:00Z',
  },
  {
    id: 'bm-4',
    url: 'https://figma.com',
    title: 'Figma',
    description: 'The collaborative interface design tool. Design, prototype, and gather feedback all in one place.',
    favicon: 'https://figma.com/favicon.ico',
    tags: ['design', 'ui', 'prototyping'],
    collectionId: 'col-design',
    notes: '',
    createdAt: '2026-03-04T11:00:00Z',
  },
  {
    id: 'bm-5',
    url: 'https://dribbble.com',
    title: 'Dribbble',
    description: 'Discover the world\'s top designers & creatives. Find design inspiration and hire talent.',
    favicon: 'https://dribbble.com/favicon.ico',
    tags: ['design', 'inspiration', 'portfolio'],
    collectionId: 'col-design',
    notes: 'Great for UI inspiration',
    createdAt: '2026-03-05T16:45:00Z',
  },
  {
    id: 'bm-6',
    url: 'https://notion.so',
    title: 'Notion',
    description: 'The all-in-one workspace for notes, tasks, wikis, and databases.',
    favicon: 'https://notion.so/favicon.ico',
    tags: ['productivity', 'notes', 'workspace'],
    collectionId: 'col-productivity',
    notes: 'Using for project management',
    createdAt: '2026-03-06T08:00:00Z',
  },
  {
    id: 'bm-7',
    url: 'https://linear.app',
    title: 'Linear',
    description: 'The issue tracking tool you\'ll enjoy using. Streamline software projects, sprints, and bug tracking.',
    favicon: 'https://linear.app/favicon.ico',
    tags: ['productivity', 'project-management', 'agile'],
    collectionId: 'col-productivity',
    notes: '',
    createdAt: '2026-03-07T13:20:00Z',
  },
  {
    id: 'bm-8',
    url: 'https://vercel.com',
    title: 'Vercel',
    description: 'Develop. Preview. Ship. The best frontend developer experience.',
    favicon: 'https://vercel.com/favicon.ico',
    tags: ['deployment', 'hosting', 'frontend'],
    collectionId: 'col-dev',
    notes: 'Deploy LinkVault here',
    createdAt: '2026-03-08T10:30:00Z',
  },
  {
    id: 'bm-9',
    url: 'https://supabase.com',
    title: 'Supabase',
    description: 'The open source Firebase alternative. Build production-grade applications with a Postgres database.',
    favicon: 'https://supabase.com/favicon.ico',
    tags: ['database', 'backend', 'open-source'],
    collectionId: 'col-dev',
    notes: 'Potential backend for LinkVault v2',
    createdAt: '2026-03-09T15:00:00Z',
  },
  {
    id: 'bm-10',
    url: 'https://typescriptlang.org',
    title: 'TypeScript',
    description: 'TypeScript is a strongly typed programming language that builds on JavaScript.',
    favicon: 'https://typescriptlang.org/favicon.ico',
    tags: ['typescript', 'language', 'frontend'],
    collectionId: 'col-learning',
    notes: '',
    createdAt: '2026-03-10T09:00:00Z',
  },
  {
    id: 'bm-11',
    url: 'https://ui.shadcn.com',
    title: 'shadcn/ui',
    description: 'Beautifully designed components built with Radix UI and Tailwind CSS.',
    favicon: 'https://ui.shadcn.com/favicon.ico',
    tags: ['ui', 'components', 'react'],
    collectionId: 'col-dev',
    notes: 'Consider for component library',
    createdAt: '2026-03-11T12:00:00Z',
  },
  {
    id: 'bm-12',
    url: 'https://news.ycombinator.com',
    title: 'Hacker News',
    description: 'Social news website focusing on computer science and entrepreneurship.',
    favicon: 'https://news.ycombinator.com/favicon.ico',
    tags: ['news', 'tech', 'community'],
    collectionId: 'col-news',
    notes: 'Check daily for trends',
    createdAt: '2026-03-12T07:30:00Z',
  },
  {
    id: 'bm-13',
    url: 'https://medium.com',
    title: 'Medium',
    description: 'Where good ideas find you. Read and share ideas from independent thinkers.',
    favicon: 'https://medium.com/favicon.ico',
    tags: ['blog', 'reading', 'writing'],
    collectionId: 'col-news',
    notes: '',
    createdAt: '2026-03-13T14:00:00Z',
  },
  {
    id: 'bm-14',
    url: 'https://roadmap.sh',
    title: 'Developer Roadmaps',
    description: 'Community driven roadmaps, articles, and resources for developers.',
    favicon: 'https://roadmap.sh/favicon.ico',
    tags: ['learning', 'career', 'roadmap'],
    collectionId: 'col-learning',
    notes: 'Good reference for skill gaps',
    createdAt: '2026-03-14T11:15:00Z',
  },
  {
    id: 'bm-15',
    url: 'https://ray.so',
    title: 'Ray.so',
    description: 'Create beautiful images of your code snippets. Share with the world.',
    favicon: 'https://ray.so/favicon.ico',
    tags: ['design', 'code', 'tools'],
    collectionId: 'col-design',
    notes: 'For sharing code snippets on social',
    createdAt: '2026-03-15T16:00:00Z',
  },
  {
    id: 'bm-16',
    url: 'https://cal.com',
    title: 'Cal.com',
    description: 'The open-source scheduling infrastructure. Scheduling for everyone.',
    favicon: 'https://cal.com/favicon.ico',
    tags: ['productivity', 'scheduling', 'open-source'],
    collectionId: 'col-productivity',
    notes: '',
    createdAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'bm-17',
    url: 'https://excalidraw.com',
    title: 'Excalidraw',
    description: 'Virtual whiteboard for sketching hand-drawn like diagrams.',
    favicon: 'https://excalidraw.com/favicon.ico',
    tags: ['design', 'whiteboard', 'collaboration'],
    collectionId: 'col-design',
    notes: 'Perfect for quick architecture diagrams',
    createdAt: '2026-03-17T13:45:00Z',
  },
  {
    id: 'bm-18',
    url: 'https://zod.dev',
    title: 'Zod',
    description: 'TypeScript-first schema validation with static type inference.',
    favicon: 'https://zod.dev/favicon.ico',
    tags: ['typescript', 'validation', 'schema'],
    collectionId: 'col-learning',
    notes: 'Using in LinkVault for form validation',
    createdAt: '2026-03-18T09:30:00Z',
  },
  {
    id: 'bm-19',
    url: 'https://planetscale.com',
    title: 'PlanetScale',
    description: 'The MySQL-compatible serverless database platform.',
    favicon: 'https://planetscale.com/favicon.ico',
    tags: ['database', 'serverless', 'mysql'],
    collectionId: 'col-dev',
    notes: '',
    createdAt: '2026-03-19T15:20:00Z',
  },
  {
    id: 'bm-20',
    url: 'https://arc.net',
    title: 'Arc Browser',
    description: 'A better way to use the internet. The browser that puts you first.',
    favicon: 'https://arc.net/favicon.ico',
    tags: ['browser', 'productivity', 'tools'],
    collectionId: 'col-productivity',
    notes: 'Primary browser',
    createdAt: '2026-03-20T11:00:00Z',
  },
];
